### PR TITLE
Support AC70 and AC70P Device

### PR DESCRIPTION
**Pull request by matthewpucc**
I added support for AC70 and AC70P based on comments in #111 . This is tested and working on the AC70 but I don't have access to an AC70P

### CODE REVIEW

**Comment by matthewpucc** [comment]
I'm going to do a bit more digging here. Don't merge yet.

**Comment by matthewpucc** [comment]
If you have a guide on how to hack on this and figure out uint fields like ac power output for v2, let me know. I'm very interested in that data.

**Comment by kvanonavk** [comment]
> If you have a guide on how to hack on this and figure out uint fields like ac power output for v2, let me know. I'm very interested in that data.

Hi. You can check my pull request for AC180P. Those fields I've added should work for AC70(P) too. Here is the link: https://github.com/Patrick762/hassio-bluetti-bt/pull/119

**Comment by matthewpucc** [comment]
nice. thanks @kvanonavk , ill pull this in once it gets merged

**Pull request merged**
