### PR TITLE
Version 0.0.11

### PR DESCRIPTION
**Pull request by Patrick762**

### CODE REVIEW

**Comment by Patrick762** [comment]
@SupaFlav can you test this version? I made some changes to get the EP600 working again. The battery pack polling also doesn't seem to work with the AC300. But that can be fixed in another release

**Comment by SupaFlav** [comment]
I'll try to take a look early this week.

Polling of packs seems to work fine for AC200M, but I still get plagued by a bluetooth issue every few days that requires me to restart the system (not just HA).  Something deeper down in the drivers/bluetooth layers seems to get messed up.  I have an automation in place to reboot the system after an extended timeout of reporting and then all is well again.

**Comment by Patrick762** [comment]
Got the same bug. Logs have no info in it, why this happens

**Comment by SupaFlav** [comment]
Not sure, it seems to be intermittent and can happen after a day or nothing after a week.  As I mentioned, I have a timeout via automation for the battery reporting that restarts HA and then all is well again.  Interim solution at least.

Been pretty busy this past week and likely for the next, but hope to spend a bit of time on this next week.

**Comment by SupaFlav** [comment]
Been MIA, life and such, but I noticed the new HA OS 11.0 release with many BlueX & BT updates.  Hopefully this clears up some of these connection issues being experience.  Unable to dedicate time at the moment, but will try it out when I can.

**Comment by Patrick762** [comment]
Seems like it no longer disconnected on my installation

**Comment by Patrick762** [comment]
Found a new problem: In non persistent connections, the return value of the coordinator seems to be always None

**Comment by Patrick762** [comment]
Seems like the non-persistent connections are now fixed. I'll test it for 2 days and if everything works, the new version is ready

**Pull request merged**
